apiVersion: v1
kind: Service
metadata:
  name: test-nginx-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
  labels:
    env: dev
spec:
  selector:
    app: test-nginx-service
