apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 992382362423.dkr.ecr.ap-northeast-2.amazonaws.com/eks-frontend
  newName: 992382362423.dkr.ecr.ap-northeast-2.amazonaws.com/eks-frontend
  newTag: 0162aff6
resources:
- ../../base
patchesStrategicMerge:
- test-nginx-patch.yaml
- alb-service-patch.yaml
