apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
